name: Build Gradle project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout project sources
      uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Build
      run: ./gradlew build -x test -x checkStyleMain -x checkStyleTest

    - name: Check-Style Main
      run: ./gradlew checkStyleMain

    - name: Check-Style Test
      run: ./gradlew checkStyleTest

    - name: Unit tests
      run: ./gradlew test

