name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout project sources
      uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Run build
      run: ./gradlew build -x test -x checkStyleMain -x checkStyleTest

    - name: Run checkStyleMain
      run: ./gradlew checkStyleMain

    - name: Run checkStyleTest
      run: ./gradlew checkStyleTest

    - name: Run tests with Gradle Wrapper
      run: ./gradlew test

    - name: SonarCloud Scan
    # You may pin to the exact commit or the version.
    # uses: SonarSource/sonarcloud-github-action@4b4d7634dab97dcee0b75763a54a6dc92a9e6bc1
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

